---
version: '3'

services:
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile.sandbox
      args:
        user_id: ${SANDBOX_USER_ID}
        user_name: ${SANDBOX_USER_NAME}
        group_id: ${SANDBOX_GROUP_ID}
        group_name: ${SANDBOX_GROUP_NAME}
    image: codeclub/web-app:sandbox
    hostname: web-app  # For nice label on shell prompt.
    entrypoint: /bin/bash
    volumes:
      # Note the paths are relative to project root.
      - ./web-app:/srv/application
    environment:
      - WEB_API_BASE_URL=http://api.development.sandbox
    stdin_open: true
    tty: true
